import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../theme/appTheme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.paper },
  centerFill: { flex: 1, justifyContent: "center", alignItems: "center" },
  streakRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 4,
    paddingBottom: 12,
    gap: 6,
  },
  streakValue: { color: COLORS.waxSeal, fontFamily: FONTS.monoBold, fontSize: 13, letterSpacing: 0.5 },
  streakLabel: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 11, letterSpacing: 1 },
  dateLabel: {
    color: COLORS.inkFaint,
    fontFamily: FONTS.mono,
    fontSize: 10,
    letterSpacing: 1.5,
    textAlign: "center",
    marginBottom: 4,
  },
  pairContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 12,
    paddingBottom: 16,
  },
  bookend: { color: COLORS.ink, fontSize: 24, fontFamily: FONTS.display, letterSpacing: 0.5 },
  arrow: { color: COLORS.inkFaint, fontSize: 20, marginHorizontal: 12 },
  attemptsLeft: {
    color: COLORS.inkFaint,
    fontFamily: FONTS.mono,
    fontSize: 10,
    textAlign: "center",
    letterSpacing: 1,
    marginBottom: 8,
  },
  hintRow: { alignItems: "center", marginBottom: 12 },
  hintText: {
    color: COLORS.ink,
    fontFamily: FONTS.monoBold,
    fontSize: 15,
    letterSpacing: 3,
    marginBottom: 4,
  },
  hintButtonText: {
    color: COLORS.waxSealMuted,
    fontFamily: FONTS.mono,
    fontSize: 10,
    letterSpacing: 1,
    textDecorationLine: "underline",
  },
  bestPanel: {
    alignSelf: "center",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 16,
    backgroundColor: COLORS.paperPanel,
  },
  bestPanelLabel: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 10, letterSpacing: 1.5 },
  bestPanelScore: { fontSize: 22, fontFamily: FONTS.monoBold, marginTop: 2 },
  bestPanelWord: { color: COLORS.inkMuted, fontSize: 13, marginTop: 2, letterSpacing: 1 },
  bestPanelEmpty: {
    alignSelf: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.hairline,
    borderRadius: 4,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 16,
  },
  bestPanelEmptyText: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 12, marginTop: 2 },
  inputRow: { flexDirection: "row", paddingHorizontal: 20, marginBottom: 8 },
  input: {
    flex: 1,
    backgroundColor: COLORS.paperPanelRaised,
    color: COLORS.ink,
    borderRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: COLORS.hairline,
  },
  submitButton: {
    backgroundColor: COLORS.waxSeal,
    borderRadius: 4,
    paddingHorizontal: 20,
    justifyContent: "center",
    marginLeft: 8,
  },
  submitButtonText: { color: COLORS.paper, fontFamily: FONTS.monoBold, fontSize: 15 },
  collectionToast: {
    color: COLORS.waxSeal,
    fontFamily: FONTS.mono,
    textAlign: "center",
    fontSize: 11,
    marginBottom: 12,
    paddingHorizontal: 20,
  },
  findsList: { flex: 1, paddingHorizontal: 20 },
  findRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.hairline,
  },
  findWord: { color: COLORS.ink, fontSize: 15 },
  findTier: { fontFamily: FONTS.mono, fontSize: 12 },
  // Result / already-played state
  resultHeading: {
    color: COLORS.inkFaint,
    fontFamily: FONTS.mono,
    fontSize: 12,
    letterSpacing: 3,
    marginBottom: 8,
    textAlign: "center",
  },
  resultSub: {
    color: COLORS.inkMuted,
    fontFamily: FONTS.mono,
    fontSize: 11,
    letterSpacing: 1,
    marginBottom: 24,
    textAlign: "center",
  },
  resultBestLabel: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 11, letterSpacing: 1 },
  resultBestWord: {
    color: COLORS.ink,
    fontSize: 32,
    fontFamily: FONTS.display,
    marginTop: 8,
    letterSpacing: 0.5,
  },
  resultBestScore: { fontSize: 44, fontFamily: FONTS.monoBold, marginTop: 10 },
  resultBestTier: { color: COLORS.inkMuted, fontFamily: FONTS.mono, fontSize: 13, marginTop: 4, letterSpacing: 1 },
  shareButton: {
    marginTop: 20,
    borderWidth: 1,
    borderColor: COLORS.waxSeal,
    borderRadius: 4,
    paddingHorizontal: 24,
    paddingVertical: 10,
  },
  shareButtonText: { color: COLORS.waxSeal, fontFamily: FONTS.monoBold, fontSize: 12, letterSpacing: 1.5 },
  offscreenCapture: { position: "absolute", top: 0, left: -2000 },
  streakBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 28,
    gap: 8,
  },
  streakBadge: {
    borderWidth: 1,
    borderColor: COLORS.waxSeal,
    borderRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignItems: "center",
  },
  streakBadgeValue: { color: COLORS.waxSeal, fontFamily: FONTS.monoBold, fontSize: 20 },
  streakBadgeLabel: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 9, letterSpacing: 1 },
  comeBackText: {
    color: COLORS.inkFaint,
    fontFamily: FONTS.mono,
    fontSize: 11,
    letterSpacing: 1,
    marginTop: 32,
    textAlign: "center",
  },
});
