import { StyleSheet } from "react-native";
import { COLORS, FONTS, DEPTH } from "../theme/appTheme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  centerFill: { flex: 1, justifyContent: "center", alignItems: "center" },
  streakRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 10,
    paddingBottom: 4,
    gap: 6,
  },
  streakValue: { color: COLORS.primary, fontFamily: FONTS.monoBold, fontSize: 15, letterSpacing: 0.5 },
  streakLabel: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 11, letterSpacing: 1 },

  pairCard: { marginHorizontal: 20, marginTop: 10, marginBottom: 14, paddingVertical: 22 },
  pairRow: { flexDirection: "row", justifyContent: "center", alignItems: "center", flexWrap: "wrap" },
  bookend: { color: COLORS.ink, fontSize: 24, fontFamily: FONTS.display, letterSpacing: 0.5 },
  arrowPill: {
    backgroundColor: COLORS.primary,
    borderWidth: 2,
    borderColor: COLORS.outline,
    borderRadius: 999,
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 12,
  },
  arrow: { color: COLORS.cream, fontSize: 15, fontFamily: FONTS.monoBold },

  attemptsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 22,
    marginBottom: 4,
  },
  attemptsLeft: { color: COLORS.inkMuted, fontFamily: FONTS.monoBold, fontSize: 10, letterSpacing: 0.5 },
  hintButtonText: {
    color: COLORS.primary,
    fontFamily: FONTS.monoBold,
    fontSize: 10,
    letterSpacing: 0.5,
    textDecorationLine: "underline",
  },
  hintText: {
    color: COLORS.ink,
    fontFamily: FONTS.monoBold,
    fontSize: 16,
    letterSpacing: 3,
    textAlign: "center",
    marginTop: 6,
    marginBottom: 4,
  },

  bestPanelInner: { alignItems: "center", paddingVertical: 12, marginHorizontal: 20, marginTop: 12, marginBottom: 4 },
  bestPanelLabel: { color: COLORS.inkFaint, fontFamily: FONTS.monoBold, fontSize: 10, letterSpacing: 1.5 },
  bestPanelScore: { fontSize: 22, fontFamily: FONTS.monoBold, marginTop: 2 },
  bestPanelWord: { color: COLORS.inkMuted, fontFamily: FONTS.display, fontSize: 15, marginTop: 2, letterSpacing: 0.5 },
  bestPanelEmpty: {
    alignSelf: "center",
    alignItems: "center",
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: COLORS.inkFaint,
    borderRadius: DEPTH.radiusMd,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 4,
  },
  bestPanelEmptyText: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 12, marginTop: 2 },

  inputRow: { flexDirection: "row", alignItems: "flex-start", paddingHorizontal: 20, marginBottom: 8 },
  input: {
    flex: 1,
    backgroundColor: COLORS.surfaceAlt,
    color: COLORS.ink,
    borderRadius: DEPTH.radiusMd,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: FONTS.display,
    borderWidth: DEPTH.borderWidth,
    borderColor: COLORS.outline,
  },
  goButton: { marginLeft: 10, width: 64 },

  collectionToast: {
    color: COLORS.secondary,
    fontFamily: FONTS.monoBold,
    textAlign: "center",
    fontSize: 11,
    marginBottom: 12,
    paddingHorizontal: 20,
  },
  tip: {
    color: COLORS.inkFaint,
    fontSize: 12,
    lineHeight: 17,
    textAlign: "center",
    paddingHorizontal: 40,
    marginTop: 8,
  },
  findsList: { flex: 1, paddingHorizontal: 20 },
  findRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.hairline,
  },
  findDot: { width: 8, height: 8, borderRadius: 4, marginRight: 10 },
  findWord: { color: COLORS.ink, fontSize: 15, fontFamily: FONTS.displaySemi, flex: 1 },
  findTier: { fontFamily: FONTS.mono, fontSize: 11 },

  // Result / already-played state
  resultHeading: {
    color: COLORS.inkFaint,
    fontFamily: FONTS.monoBold,
    fontSize: 12,
    letterSpacing: 3,
    marginBottom: 8,
    textAlign: "center",
  },
  resultSub: {
    color: COLORS.inkMuted,
    fontFamily: FONTS.mono,
    fontSize: 11,
    letterSpacing: 1,
    marginBottom: 24,
    textAlign: "center",
  },
  resultBestCardInner: { alignItems: "center", paddingVertical: 20, width: "100%" },
  resultBestLabel: { color: COLORS.inkFaint, fontFamily: FONTS.monoBold, fontSize: 11, letterSpacing: 1 },
  resultBestWord: { color: COLORS.ink, fontSize: 28, fontFamily: FONTS.display, marginTop: 8 },
  resultBestScore: { fontSize: 38, fontFamily: FONTS.monoBold, marginTop: 8 },
  resultBestTier: { fontFamily: FONTS.monoBold, fontSize: 13, marginTop: 4, letterSpacing: 1.5 },
  streakBadgeRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", marginTop: 28, gap: 12 },
  streakBadge: {
    borderWidth: 2,
    borderColor: COLORS.outline,
    borderRadius: DEPTH.radiusSm,
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: COLORS.surface,
  },
  streakBadgeValue: { color: COLORS.primary, fontFamily: FONTS.monoBold, fontSize: 20 },
  streakBadgeLabel: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 9, letterSpacing: 1 },
  comeBackText: {
    color: COLORS.inkFaint,
    fontFamily: FONTS.mono,
    fontSize: 11,
    letterSpacing: 1,
    marginTop: 32,
    textAlign: "center",
  },
  offscreenCapture: { position: "absolute", top: 0, left: -2000 },
});
