import { StyleSheet } from "react-native";
import { COLORS, FONTS, DEPTH } from "../theme/appTheme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  errorText: { color: COLORS.inkMuted, textAlign: "center", marginBottom: 16 },

  pairCard: { marginHorizontal: 20, marginTop: 16, marginBottom: 14, paddingVertical: 22 },
  pairRow: { flexDirection: "row", justifyContent: "center", alignItems: "center", flexWrap: "wrap" },
  bookend: { color: COLORS.ink, fontSize: 26, fontFamily: FONTS.display, letterSpacing: 0.5 },
  arrowPill: {
    backgroundColor: COLORS.primary,
    borderWidth: 2,
    borderColor: COLORS.outline,
    borderRadius: 999,
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 12,
  },
  arrow: { color: COLORS.cream, fontSize: 16, fontFamily: FONTS.monoBold },

  attemptsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 22,
    marginBottom: 4,
  },
  attemptsLeft: { color: COLORS.inkMuted, fontFamily: FONTS.monoBold, fontSize: 11, letterSpacing: 1 },
  hintButtonText: {
    color: COLORS.primary,
    fontFamily: FONTS.monoBold,
    fontSize: 10,
    letterSpacing: 0.5,
    textDecorationLine: "underline",
  },
  hintText: {
    color: COLORS.ink,
    fontFamily: FONTS.monoBold,
    fontSize: 16,
    letterSpacing: 3,
    textAlign: "center",
    marginTop: 6,
    marginBottom: 4,
  },

  bestPanelInner: { alignItems: "center", paddingVertical: 12, marginHorizontal: 20, marginTop: 12, marginBottom: 4 },
  bestPanelLabel: { color: COLORS.inkFaint, fontFamily: FONTS.monoBold, fontSize: 10, letterSpacing: 1.5 },
  bestPanelScore: { fontSize: 22, fontFamily: FONTS.monoBold, marginTop: 2 },
  bestPanelWord: { color: COLORS.inkMuted, fontFamily: FONTS.display, fontSize: 15, marginTop: 2, letterSpacing: 0.5 },
  bestPanelEmpty: {
    alignSelf: "center",
    alignItems: "center",
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: COLORS.inkFaint,
    borderRadius: DEPTH.radiusMd,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 4,
  },
  bestPanelEmptyText: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 12, marginTop: 2 },

  inputRow: { flexDirection: "row", alignItems: "flex-start", paddingHorizontal: 20, marginBottom: 10 },
  input: {
    flex: 1,
    backgroundColor: COLORS.surfaceAlt,
    color: COLORS.ink,
    borderRadius: DEPTH.radiusMd,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: FONTS.display,
    borderWidth: DEPTH.borderWidth,
    borderColor: COLORS.outline,
  },
  goButton: { marginLeft: 10, width: 64 },

  collectionToast: {
    color: COLORS.secondary,
    fontFamily: FONTS.monoBold,
    textAlign: "center",
    fontSize: 11,
    marginBottom: 12,
    paddingHorizontal: 20,
  },
  tip: {
    color: COLORS.inkFaint,
    fontSize: 12,
    lineHeight: 17,
    textAlign: "center",
    paddingHorizontal: 40,
    marginTop: 8,
    marginBottom: 8,
  },
  findsList: { flex: 1, paddingHorizontal: 20 },
  findRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.hairline,
  },
  findDot: { width: 8, height: 8, borderRadius: 4, marginRight: 10 },
  findWord: { color: COLORS.ink, fontSize: 15, fontFamily: FONTS.displaySemi, flex: 1 },
  findTier: { fontFamily: FONTS.mono, fontSize: 11 },

  newPairButton: { marginHorizontal: 20, marginTop: 6, marginBottom: 14 },

  // Result / round-over state
  endScreen: { flex: 1, paddingHorizontal: 20, paddingTop: 24, alignItems: "center" },
  endHeading: { color: COLORS.inkFaint, fontFamily: FONTS.monoBold, fontSize: 12, letterSpacing: 3, marginBottom: 16 },
  endBestCardInner: { alignItems: "center", paddingVertical: 20, width: "100%" },
  endBestLabel: { color: COLORS.inkFaint, fontFamily: FONTS.monoBold, fontSize: 11, letterSpacing: 1 },
  endBestWord: { color: COLORS.ink, fontSize: 30, fontFamily: FONTS.display, marginTop: 8 },
  endBestScore: { fontSize: 40, fontFamily: FONTS.monoBold, marginTop: 8 },
  endBestTier: { fontFamily: FONTS.monoBold, fontSize: 13, marginTop: 4, letterSpacing: 1.5 },
  endCollectionBadge: {
    color: COLORS.secondary,
    fontFamily: FONTS.monoBold,
    fontSize: 12,
    marginTop: 14,
    letterSpacing: 1,
  },
  endStatsRow: { flexDirection: "row", marginTop: 28, gap: 40 },
  endStat: { alignItems: "center" },
  endStatValue: { color: COLORS.ink, fontSize: 26, fontFamily: FONTS.monoBold },
  endStatLabel: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 9, letterSpacing: 1, marginTop: 2 },

  offscreenCapture: { position: "absolute", top: 0, left: -2000 },
});
