import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../theme/appTheme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.paper },
  pairContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 32,
    paddingBottom: 16,
  },
  bookend: {
    color: COLORS.ink,
    fontSize: 24,
    fontFamily: FONTS.display,
    letterSpacing: 0.5,
  },
  arrow: { color: COLORS.inkFaint, fontSize: 20, marginHorizontal: 12 },
  attemptsLeft: {
    color: COLORS.inkFaint,
    fontFamily: FONTS.mono,
    fontSize: 10,
    textAlign: "center",
    letterSpacing: 1,
    marginBottom: 8,
  },
  hintRow: { alignItems: "center", marginBottom: 12 },
  hintText: {
    color: COLORS.ink,
    fontFamily: FONTS.monoBold,
    fontSize: 15,
    letterSpacing: 3,
    marginBottom: 4,
  },
  hintButtonText: {
    color: COLORS.waxSealMuted,
    fontFamily: FONTS.mono,
    fontSize: 10,
    letterSpacing: 1,
    textDecorationLine: "underline",
  },
  bestPanel: {
    alignSelf: "center",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 16,
    backgroundColor: COLORS.paperPanel,
  },
  bestPanelLabel: {
    color: COLORS.inkFaint,
    fontFamily: FONTS.mono,
    fontSize: 10,
    letterSpacing: 1.5,
  },
  bestPanelScore: { fontSize: 22, fontFamily: FONTS.monoBold, marginTop: 2 },
  bestPanelWord: { color: COLORS.inkMuted, fontSize: 13, marginTop: 2, letterSpacing: 1 },
  bestPanelEmpty: {
    alignSelf: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.hairline,
    borderRadius: 4,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 16,
  },
  bestPanelEmptyText: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 12, marginTop: 2 },
  inputRow: { flexDirection: "row", paddingHorizontal: 20, marginBottom: 8 },
  input: {
    flex: 1,
    backgroundColor: COLORS.paperPanelRaised,
    color: COLORS.ink,
    borderRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: COLORS.hairline,
  },
  submitButton: {
    backgroundColor: COLORS.waxSeal,
    borderRadius: 4,
    paddingHorizontal: 20,
    justifyContent: "center",
    marginLeft: 8,
  },
  submitButtonText: { color: COLORS.paper, fontFamily: FONTS.monoBold, fontSize: 15 },
  collectionToast: {
    color: COLORS.waxSeal,
    fontFamily: FONTS.mono,
    textAlign: "center",
    fontSize: 11,
    marginBottom: 12,
    paddingHorizontal: 20,
  },
  findsList: { flex: 1, paddingHorizontal: 20 },
  findRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.hairline,
  },
  findWord: { color: COLORS.ink, fontSize: 15 },
  findTier: { fontFamily: FONTS.mono, fontSize: 12 },
  emptyText: { color: COLORS.inkFaint, textAlign: "center", marginTop: 40 },
  newPairButton: {
    margin: 20,
    backgroundColor: COLORS.paperPanelRaised,
    borderRadius: 4,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.hairline,
  },
  newPairButtonText: { color: COLORS.ink, fontFamily: FONTS.monoBold, fontSize: 14 },
  errorText: { color: COLORS.ink, textAlign: "center", marginTop: 100, marginBottom: 20 },
  button: {
    alignSelf: "center",
    backgroundColor: COLORS.waxSeal,
    borderRadius: 4,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  buttonText: { color: COLORS.paper, fontFamily: FONTS.monoBold },
  endScreen: { flex: 1, justifyContent: "center", alignItems: "center", paddingHorizontal: 24 },
  endHeading: {
    color: COLORS.inkFaint,
    fontFamily: FONTS.mono,
    fontSize: 12,
    letterSpacing: 3,
    marginBottom: 28,
  },
  endBestLabel: { color: COLORS.inkFaint, fontFamily: FONTS.mono, fontSize: 11, letterSpacing: 1 },
  endBestWord: {
    color: COLORS.ink,
    fontSize: 32,
    fontFamily: FONTS.display,
    marginTop: 8,
    letterSpacing: 0.5,
  },
  endBestScore: { fontSize: 44, fontFamily: FONTS.monoBold, marginTop: 10 },
  endBestTier: {
    color: COLORS.inkMuted,
    fontFamily: FONTS.mono,
    fontSize: 13,
    marginTop: 4,
    letterSpacing: 1,
  },
  endCollectionBadge: {
    color: COLORS.waxSeal,
    fontFamily: FONTS.mono,
    fontSize: 11,
    marginTop: 14,
    letterSpacing: 1,
  },
  shareButton: {
    marginTop: 20,
    borderWidth: 1,
    borderColor: COLORS.waxSeal,
    borderRadius: 4,
    paddingHorizontal: 24,
    paddingVertical: 10,
  },
  shareButtonText: {
    color: COLORS.waxSeal,
    fontFamily: FONTS.monoBold,
    fontSize: 12,
    letterSpacing: 1.5,
  },
  offscreenCapture: { position: "absolute", top: 0, left: -2000 },
  endStatsRow: { flexDirection: "row", marginTop: 36, gap: 40 },
  endStat: { alignItems: "center" },
  endStatValue: { color: COLORS.ink, fontSize: 20, fontFamily: FONTS.monoBold },
  endStatLabel: {
    color: COLORS.inkFaint,
    fontFamily: FONTS.mono,
    fontSize: 9,
    marginTop: 2,
    letterSpacing: 1,
  },
  collectionLinkButton: { paddingVertical: 10 },
  collectionLinkText: {
    color: COLORS.waxSeal,
    fontFamily: FONTS.mono,
    fontSize: 12,
    letterSpacing: 1.5,
  },
});
