import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../theme/appTheme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.ledgerInk },
  pairContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 32,
    paddingBottom: 16,
  },
  bookend: {
    color: COLORS.parchment,
    fontSize: 24,
    fontFamily: FONTS.display,
    letterSpacing: 0.5,
  },
  arrow: { color: COLORS.parchmentFaint, fontSize: 20, marginHorizontal: 12 },
  attemptsLeft: {
    color: COLORS.parchmentFaint,
    fontFamily: FONTS.mono,
    fontSize: 10,
    textAlign: "center",
    letterSpacing: 1,
    marginBottom: 8,
  },
  bestPanel: {
    alignSelf: "center",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 16,
    backgroundColor: COLORS.vellumPanel,
  },
  bestPanelLabel: {
    color: COLORS.parchmentFaint,
    fontFamily: FONTS.mono,
    fontSize: 10,
    letterSpacing: 1.5,
  },
  bestPanelScore: { fontSize: 22, fontFamily: FONTS.monoBold, marginTop: 2 },
  bestPanelWord: { color: COLORS.parchmentMuted, fontSize: 13, marginTop: 2, letterSpacing: 1 },
  inputRow: { flexDirection: "row", paddingHorizontal: 20, marginBottom: 8 },
  input: {
    flex: 1,
    backgroundColor: COLORS.vellumPanelRaised,
    color: COLORS.parchment,
    borderRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: COLORS.hairline,
  },
  submitButton: {
    backgroundColor: COLORS.waxSeal,
    borderRadius: 4,
    paddingHorizontal: 20,
    justifyContent: "center",
    marginLeft: 8,
  },
  submitButtonText: { color: COLORS.ledgerInk, fontFamily: FONTS.monoBold, fontSize: 15 },
  collectionToast: {
    color: COLORS.waxSeal,
    fontFamily: FONTS.mono,
    textAlign: "center",
    fontSize: 11,
    marginBottom: 12,
    paddingHorizontal: 20,
  },
  findsList: { flex: 1, paddingHorizontal: 20 },
  findRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.hairline,
  },
  findWord: { color: COLORS.parchment, fontSize: 15 },
  findTier: { fontFamily: FONTS.mono, fontSize: 12 },
  emptyText: { color: COLORS.parchmentFaint, textAlign: "center", marginTop: 40 },
  newPairButton: {
    margin: 20,
    backgroundColor: COLORS.vellumPanelRaised,
    borderRadius: 4,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.hairline,
  },
  newPairButtonText: { color: COLORS.parchment, fontFamily: FONTS.monoBold, fontSize: 14 },
  errorText: { color: COLORS.parchment, textAlign: "center", marginTop: 100, marginBottom: 20 },
  button: {
    alignSelf: "center",
    backgroundColor: COLORS.waxSeal,
    borderRadius: 4,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  buttonText: { color: COLORS.ledgerInk, fontFamily: FONTS.monoBold },
  endScreen: { flex: 1, justifyContent: "center", alignItems: "center", paddingHorizontal: 24 },
  endHeading: {
    color: COLORS.parchmentFaint,
    fontFamily: FONTS.mono,
    fontSize: 12,
    letterSpacing: 3,
    marginBottom: 28,
  },
  endBestLabel: { color: COLORS.parchmentFaint, fontFamily: FONTS.mono, fontSize: 11, letterSpacing: 1 },
  endBestWord: {
    color: COLORS.parchment,
    fontSize: 32,
    fontFamily: FONTS.display,
    marginTop: 8,
    letterSpacing: 0.5,
  },
  endBestScore: { fontSize: 44, fontFamily: FONTS.monoBold, marginTop: 10 },
  endBestTier: {
    color: COLORS.parchmentMuted,
    fontFamily: FONTS.mono,
    fontSize: 13,
    marginTop: 4,
    letterSpacing: 1,
  },
  endCollectionBadge: {
    color: COLORS.waxSeal,
    fontFamily: FONTS.mono,
    fontSize: 11,
    marginTop: 14,
    letterSpacing: 1,
  },
  endStatsRow: { flexDirection: "row", marginTop: 36, gap: 40 },
  endStat: { alignItems: "center" },
  endStatValue: { color: COLORS.parchment, fontSize: 20, fontFamily: FONTS.monoBold },
  endStatLabel: {
    color: COLORS.parchmentFaint,
    fontFamily: FONTS.mono,
    fontSize: 9,
    marginTop: 2,
    letterSpacing: 1,
  },
  collectionLinkButton: { paddingVertical: 10 },
  collectionLinkText: {
    color: COLORS.waxSeal,
    fontFamily: FONTS.mono,
    fontSize: 12,
    letterSpacing: 1.5,
  },
});
